version: '3.8'

services:
  app1:
    build: ./app1
    expose:
      - 8000
    networks:
      - webnet

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
    networks:
      - webnet

networks:
  webnet:
